# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad5afd673fdfa26ed259cb9be0d7e73b76daca8bcdbe724ed02690aabd5ef6df0f02846c144529539f21814ab0e742b3bad478f5f9b549c7e7f523687fee8c71

test:
  secret_key_base: 4a2a3ec46bbf0c7c921ae3cee5767bc165fba42ff0ecff0510d9d73afb6b36057da84e0560fa7532a15f5c1f27fecf6a9159963deee9feb2cd32231514120319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
