# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Job.create!([
  {latitude: "43.655987", longitude: "-79.379443", title: "DMZ Job", posted_at: nil, address: nil},
  {latitude: nil, longitude: nil, title: "Awesome Job", posted_at: nil, address: "55 Maitland St, Toronto, ON"}
])
Location.create!([
  {gov_id: 23347, name: "King City, ON"},
  {gov_id: 23187, name: "Ajax, ON"},
  {gov_id: 45077, name: "Stouffville, ON"},
  {gov_id: 43624, name: "Brougham, ON"},
  {gov_id: 23186, name: "Whitchurch-Stouffville, ON"},
  {gov_id: 51516, name: "Lakeside, ON"},
  {gov_id: 23369, name: "Bolton, ON"},
  {gov_id: 45743, name: "Hornby, ON"},
  {gov_id: 23167, name: "Aurora, ON"},
  {gov_id: 23370, name: "Georgetown, ON"},
  {gov_id: 33303, name: "Kettleby, ON"},
  {gov_id: 50140, name: "Milton, ON"},
  {gov_id: 23185, name: "Whitby, ON"},
  {gov_id: 35911, name: "Terra Cotta, ON"},
  {gov_id: 23169, name: "Caledon, ON"},
  {gov_id: 32303, name: "Schomberg, ON"},
  {gov_id: 33877, name: "Caledon East, ON"},
  {gov_id: 23178, name: "Newmarket, ON"},
  {gov_id: 53623, name: "Headon Forest, ON"},
  {gov_id: 39349, name: "Brooklin, ON"},
  {gov_id: 32233, name: "Palgrave, ON"},
  {gov_id: 22430, name: "Burlington, ON"},
  {gov_id: 22435, name: "Oshawa, ON"},
  {gov_id: 43615, name: "Ashburn, ON"},
  {gov_id: 32076, name: "Holland Landing, ON"},
  {gov_id: 32677, name: "Sharon, ON"},
  {gov_id: 23171, name: "East Gwillimbury, ON"},
  {gov_id: 23146, name: "Niagara-on-the-Lake, ON"},
  {gov_id: 46740, name: "Campbellville, ON"},
  {gov_id: 34247, name: "Virgil, ON"},
  {gov_id: 23348, name: "Tottenham, ON"},
  {gov_id: 34250, name: "Waterdown, ON"},
  {gov_id: 51055, name: "Carlisle, ON"},
  {gov_id: 43630, name: "Courtice, ON"},
  {gov_id: 23342, name: "Beeton, ON"},
  {gov_id: 22436, name: "Stoney Creek, ON"},
  {gov_id: 39078, name: "Hamilton, ON"},
  {gov_id: 35262, name: "Loretto, ON"},
  {gov_id: 50143, name: "Dundas, ON"},
  {gov_id: 50142, name: "Ancaster, ON"},
  {gov_id: 22312, name: "Edmonton, AB"},
  {gov_id: 38989, name: "Crestwood, AB"},
  {gov_id: 43418, name: "North Edmonton, AB"},
  {gov_id: 51952, name: "The Palisades, AB"},
  {gov_id: 46728, name: "Sherwood Park, AB"},
  {gov_id: 52348, name: "Sturgeon, AB"},
  {gov_id: 22320, name: "St. Albert, AB"},
  {gov_id: 52005, name: "Ellerslie, AB"},
  {gov_id: 52436, name: "Woodlands, AB"},
  {gov_id: 52006, name: "Summerside, AB"},
  {gov_id: 31653, name: "Lancaster Park, AB"},
  {gov_id: 51800, name: "Summerwood, AB"},
  {gov_id: 31473, name: "Acheson, AB"},
  {gov_id: 31686, name: "Namao, AB"},
  {gov_id: 22478, name: "Beaumont, AB"},
  {gov_id: 31778, name: "Volmer, AB"},
  {gov_id: 43097, name: "Nisku, AB"},
  {gov_id: 22437, name: "Toronto, ON"},
  {gov_id: 54175, name: "King-Spadina, ON"},
  {gov_id: 13730, name: "North Toronto, ON"},
  {gov_id: 34104, name: "Oakwood, ON"},
  {gov_id: 34324, name: "East York, ON"},
  {gov_id: 34032, name: "Leaside, ON"},
  {gov_id: 34326, name: "York, ON"},
  {gov_id: 45627, name: "Don Mills, ON"},
  {gov_id: 45634, name: "Mimico, ON"},
  {gov_id: 54133, name: "The Queensway, ON"},
  {gov_id: 34292, name: "York Mills, ON"},
  {gov_id: 44062, name: "Weston, ON"},
  {gov_id: 38959, name: "Downsview, ON"},
  {gov_id: 34325, name: "North York, ON"},
  {gov_id: 33938, name: "Etobicoke, ON"},
  {gov_id: 45641, name: "Willowdale, ON"},
  {gov_id: 32484, name: "Scarborough, ON"},
  {gov_id: 45581, name: "Thornhill, ON"},
  {gov_id: 46858, name: "Thornhill, ON"},
  {gov_id: 39079, name: "Vaughan, ON"},
  {gov_id: 33900, name: "Concord, ON"},
  {gov_id: 34157, name: "Rexdale, ON"},
  {gov_id: 34142, name: "Port Credit, ON"},
  {gov_id: 34261, name: "West Hill, ON"},
  {gov_id: 34044, name: "Malton, ON"},
  {gov_id: 22433, name: "Mississauga, ON"},
  {gov_id: 23175, name: "Markham, ON"},
  {gov_id: 34136, name: "Pine Grove, ON"},
  {gov_id: 51134, name: "Woodbridge, ON"},
  {gov_id: 23183, name: "Richmond Hill, ON"},
  {gov_id: 45079, name: "Unionville, ON"},
  {gov_id: 34049, name: "Maple, ON"},
  {gov_id: 44054, name: "Streetsville, ON"},
  {gov_id: 33895, name: "Clearview, ON"},
  {gov_id: 33857, name: "Bramalea, ON"},
  {gov_id: 32114, name: "Kleinburg, ON"},
  {gov_id: 34043, name: "Madoc, ON"},
  {gov_id: 22429, name: "Brampton, ON"},
  {gov_id: 23182, name: "Pickering, ON"},
  {gov_id: 32056, name: "Gormley, ON"},
  {gov_id: 23180, name: "Oakville, ON"},
  {gov_id: 32207, name: "Nobleton, ON"},
  {gov_id: 52841, name: "Edmonton Municipal Airport, AB"},
  {gov_id: 48575, name: "Erin Ridge, AB"},
  {gov_id: 52345, name: "Deer Ridge, AB"},
  {gov_id: 52925, name: "Rural South East, AB"},
  {gov_id: 50908, name: "Ardrossan, AB"},
  {gov_id: 51634, name: "Villeneuve, AB"},
  {gov_id: 22502, name: "Devon, AB"},
  {gov_id: 22313, name: "Fort Saskatchewan, AB"},
  {gov_id: 50957, name: "Looma, AB"},
  {gov_id: 22321, name: "Spruce Grove, AB"},
  {gov_id: 31689, name: "New Lunnon, AB"},
  {gov_id: 43036, name: "Cooking Lake, AB"},
  {gov_id: 22532, name: "Morinville, AB"},
  {gov_id: 22315, name: "Leduc, AB"},
  {gov_id: 45122, name: "Bon Accord, AB"},
  {gov_id: 22512, name: "Gibbons, AB"},
  {gov_id: 22558, name: "Stony Plain, AB"},
  {gov_id: 39090, name: "Calmar, AB"},
  {gov_id: 39113, name: "Legal, AB"},
  {gov_id: 43032, name: "Carvel, AB"},
  {gov_id: 39219, name: "Onoway, AB"},
  {gov_id: 39230, name: "Thorsby, AB"},
  {gov_id: 39126, name: "Redwater, AB"},
  {gov_id: 39112, name: "Lamont, AB"},
  {gov_id: 31115, name: "Armena, AB"},
  {gov_id: 39070, name: "Vancouver, BC"},
  {gov_id: 39069, name: "North Vancouver, BC"},
  {gov_id: 50333, name: "West Vancouver, BC"},
  {gov_id: 22327, name: "Burnaby, BC"},
  {gov_id: 22359, name: "Richmond, BC"},
  {gov_id: 22348, name: "New Westminster, BC"},
  {gov_id: 53190, name: "Howe Sound, BC"},
  {gov_id: 25001, name: "Sunshine, BC"},
  {gov_id: 51678, name: "Delta, BC"},
  {gov_id: 22354, name: "Port Moody, BC"},
  {gov_id: 22331, name: "Coquitlam, BC"},
  {gov_id: 22353, name: "Port Coquitlam, BC"},
  {gov_id: 22361, name: "Surrey, BC"},
  {gov_id: 50183, name: "Tsawwassen, BC"},
  {gov_id: 24154, name: "Pitt Meadows, BC"},
  {gov_id: 40050, name: "Maple Ridge, BC"},
  {gov_id: 22691, name: "Gibsons, BC"},
  {gov_id: 22367, name: "White Rock, BC"},
  {gov_id: 22344, name: "Langley, BC"},
  {gov_id: 48654, name: "Port Mellon, BC"},
  {gov_id: 24730, name: "Squamish, BC"},
  {gov_id: 39251, name: "Aldergrove, BC"},
  {gov_id: 39249, name: "Sechelt, BC"},
  {gov_id: 22462, name: "Regina, SK"},
  {gov_id: 23690, name: "Pilot Butte, SK"},
  {gov_id: 30472, name: "Zehner, SK"},
  {gov_id: 39686, name: "White City, SK"},
  {gov_id: 23599, name: "Balgonie, SK"},
  {gov_id: 44811, name: "Deer Valley, SK"},
  {gov_id: 23670, name: "Lumsden, SK"},
  {gov_id: 39508, name: "Craven, SK"},
  {gov_id: 23816, name: "Edenwold, SK"},
  {gov_id: 39447, name: "Rouleau, SK"},
  {gov_id: 39482, name: "Belle Plaine, SK"},
  {gov_id: 23925, name: "McLean, SK"},
  {gov_id: 39688, name: "Wilcox, SK"},
  {gov_id: 38828, name: "Lumsden Beach, SK"},
  {gov_id: 42534, name: "Riceton, SK"},
  {gov_id: 45427, name: "Corinne, SK"},
  {gov_id: 45174, name: "Regina Beach, SK"},
  {gov_id: 23761, name: "Bethune, SK"},
  {gov_id: 39478, name: "Avonlea, SK"},
  {gov_id: 23800, name: "Dilke, SK"},
  {gov_id: 39073, name: "Winnipeg, MB"},
  {gov_id: 50425, name: "North Kildonan, MB"},
  {gov_id: 40391, name: "St. Vital, MB"},
  {gov_id: 25879, name: "North Transcona, MB"},
  {gov_id: 40650, name: "West St. Paul, MB"},
  {gov_id: 40648, name: "Headingley, MB"},
  {gov_id: 25147, name: "Oakbank, MB"},
  {gov_id: 25321, name: "Rosser, MB"},
  {gov_id: 40095, name: "Lockport, MB"},
  {gov_id: 22806, name: "Lorette, MB"},
  {gov_id: 22792, name: "Stonewall, MB"},
  {gov_id: 22800, name: "Selkirk, MB"},
  {gov_id: 39265, name: "Niverville, MB"},
  {gov_id: 39271, name: "Landmark, MB"},
  {gov_id: 25946, name: "Anola, MB"},
  {gov_id: 39268, name: "Ste. Anne, MB"},
  {gov_id: 26006, name: "Elie, MB"},
  {gov_id: 25657, name: "Otterburne, MB"},
  {gov_id: 26005, name: "Blumenort, MB"},
  {gov_id: 25981, name: "Petersfield, MB"},
  {gov_id: 39259, name: "Beausejour, MB"},
  {gov_id: 25261, name: "Kleefeld, MB"},
  {gov_id: 26004, name: "Woodlands, MB"},
  {gov_id: 22801, name: "Steinbach, MB"},
  {gov_id: 26008, name: "La Broquerie, MB"},
  {gov_id: 22446, name: "Montréal, QC"},
  {gov_id: 54296, name: "Pointe-Saint-Charles, QC"},
  {gov_id: 38658, name: "Saint-Lambert, QC"},
  {gov_id: 38613, name: "Westmount, QC"},
  {gov_id: 38605, name: "Outremont, QC"},
  {gov_id: 22454, name: "Longueuil, QC"},
  {gov_id: 38652, name: "Greenfield Park, QC"},
  {gov_id: 38612, name: "Verdun, QC"},
  {gov_id: 38604, name: "Mont-Royal, QC"},
  {gov_id: 46813, name: "Brossard, QC"},
  {gov_id: 46853, name: "Ahuntsic, QC"},
  {gov_id: 38610, name: "Saint-Léonard, QC"},
  {gov_id: 38603, name: "Montréal-Ouest, QC"},
  {gov_id: 38609, name: "Saint-Laurent, QC"},
  {gov_id: 38596, name: "Anjou, QC"},
  {gov_id: 38657, name: "Saint-Hubert, QC"},
  {gov_id: 22445, name: "Laval, QC"},
  {gov_id: 38602, name: "Montréal-Nord, QC"},
  {gov_id: 38601, name: "LaSalle, QC"},
  {gov_id: 46816, name: "La Prairie, QC"},
  {gov_id: 38600, name: "Lachine, QC"},
  {gov_id: 46848, name: "Laval-des-Rapides, QC"},
  {gov_id: 38666, name: "Candiac, QC"},
  {gov_id: 38649, name: "Boucherville, QC"},
  {gov_id: 38648, name: "Montréal-Est, QC"},
  {gov_id: 38594, name: "Dorval, QC"},
  {gov_id: 52739, name: "Saint-Martin, QC"},
  {gov_id: 46832, name: "Pointe-aux-Trembles, QC"},
  {gov_id: 46837, name: "Chomedey, QC"},
  {gov_id: 38660, name: "Saint-Bruno-de-Montarville, QC"},
  {gov_id: 46817, name: "Saint-Constant, QC"},
  {gov_id: 23588, name: "Sainte-Julie, QC"},
  {gov_id: 38641, name: "Dollard-des-Ormeaux, QC"},
  {gov_id: 46798, name: "Carignan, QC"},
  {gov_id: 38656, name: "Saint-Basile-le-Grand, QC"},
  {gov_id: 38639, name: "Varennes, QC"},
  {gov_id: 23576, name: "Terrebonne, QC"},
  {gov_id: 38620, name: "Lachenaie, QC"},
  {gov_id: 38651, name: "Chambly, QC"},
  {gov_id: 38607, name: "Pointe-Claire, QC"},
  {gov_id: 46842, name: "Auteuil, QC"},
  {gov_id: 46819, name: "Châteauguay, QC"},
  {gov_id: 38606, name: "Pierrefonds, QC"},
  {gov_id: 38635, name: "Rosemère, QC"},
  {gov_id: 38628, name: "Bois-des-Filion, QC"},
  {gov_id: 38654, name: "Lorraine, QC"},
  {gov_id: 38599, name: "Kirkland, QC"},
  {gov_id: 38627, name: "Boisbriand, QC"},
  {gov_id: 51671, name: "Sainte-Geneviève, QC"},
  {gov_id: 46567, name: "L'Île-Bizard, QC"},
  {gov_id: 38598, name: "Beaconsfield, QC"},
  {gov_id: 38669, name: "Mercier, QC"},
  {gov_id: 38634, name: "Mascouche, QC"},
  {gov_id: 38637, name: "Sainte-Thérèse, QC"},
  {gov_id: 38645, name: "Repentigny, QC"},
  {gov_id: 38633, name: "Le Gardeur, QC"},
  {gov_id: 38643, name: "Saint-Eustache, QC"},
  {gov_id: 38659, name: "Beloeil, QC"},
  {gov_id: 23569, name: "Saint-Rémi, QC"},
  {gov_id: 36700, name: "Saint-Mathieu-de-Beloeil, QC"},
  {gov_id: 23544, name: "Mont-Saint-Hilaire, QC"},
  {gov_id: 38642, name: "Sainte-Marthe-sur-le-Lac, QC"},
  {gov_id: 38597, name: "Baie-d'Urfé, QC"},
  {gov_id: 38626, name: "Blainville, QC"},
  {gov_id: 39377, name: "Marieville, QC"},
  {gov_id: 36884, name: "Senneville, QC"},
  {gov_id: 23564, name: "Saint-Jean-sur-Richelieu, QC"},
  {gov_id: 38623, name: "Sainte-Anne-de-Bellevue, QC"},
  {gov_id: 38448, name: "Saint-Jean-Baptiste, QC"},
  {gov_id: 39380, name: "Sainte-Anne-des-Plaines, QC"},
  {gov_id: 36469, name: "Mont-Saint-Grégoire, QC"},
  {gov_id: 23545, name: "Pincourt, QC"},
  {gov_id: 38632, name: "L'Assomption, QC"},
  {gov_id: 38622, name: "Mirabel, QC"},
  {gov_id: 38644, name: "Vaudreuil-Dorion, QC"},
  {gov_id: 38638, name: "Saint-Jérôme, QC"},
  {gov_id: 36824, name: "Lavaltrie, QC"},
  {gov_id: 36673, name: "Saint-Jacques, QC"},
  {gov_id: 23589, name: "Saint-Hyacinthe, QC"},
  {gov_id: 36819, name: "Lacolle, QC"},
  {gov_id: 36815, name: "Henryville, QC"},
  {gov_id: 38625, name: "Bellefeuille, QC"},
  {gov_id: 23572, name: "Salaberry-de-Valleyfield, QC"},
  {gov_id: 46566, name: "Sainte-Adèle, QC"},
  {gov_id: 23465, name: "Huntingdon, QC"},
  {gov_id: 22390, name: "Halifax, NS"},
  {gov_id: 22389, name: "Dartmouth, NS"},
  {gov_id: 41907, name: "Cole Harbour, NS"},
  {gov_id: 28375, name: "Eastern Passage, NS"},
  {gov_id: 28325, name: "Beechville, NS"},
  {gov_id: 28419, name: "Goodwood, NS"},
  {gov_id: 28465, name: "Lakeside, NS"},
  {gov_id: 28152, name: "Bedford, NS"},
  {gov_id: 42065, name: "Lower Sackville, NS"},
  {gov_id: 28440, name: "Hatchet Lake, NS"},
  {gov_id: 28382, name: "East Preston, NS"},
  {gov_id: 28116, name: "Waverley, NS"},
  {gov_id: 28878, name: "Fall River, NS"},
  {gov_id: 41973, name: "Middle Sackville, NS"},
  {gov_id: 28221, name: "Beaver Bank, NS"},
  {gov_id: 28645, name: "Upper Sackville, NS"},
  {gov_id: 50830, name: "Upper Tantallon, NS"},
  {gov_id: 28417, name: "Goffs, NS"},
  {gov_id: 28430, name: "Hacketts Cove, NS"},
  {gov_id: 28874, name: "Enfield, NS"},
  {gov_id: 28871, name: "Elmsdale, NS"},
  {gov_id: 29146, name: "Musquodoboit Harbour, NS"},
  {gov_id: 29027, name: "Lantz, NS"},
  {gov_id: 28728, name: "Blandford, NS"},
  {gov_id: 28376, name: "East Jeddore, NS"},
  {gov_id: 29387, name: "Upper Nine Mile River, NS"},
  {gov_id: 28146, name: "Shubenacadie, NS"},
  {gov_id: 29436, name: "West Gore, NS"},
  {gov_id: 29360, name: "Three Mile Plains, NS"},
  {gov_id: 39314, name: "Windsor, NS"},
  {gov_id: 28879, name: "Falmouth, NS"},
  {gov_id: 39312, name: "Hantsport, NS"},
  {gov_id: 22382, name: "Moncton, NB"},
  {gov_id: 22873, name: "Dieppe, NB"},
  {gov_id: 22876, name: "Riverview, NB"},
  {gov_id: 40959, name: "Memramcook, NB"},
  {gov_id: 26210, name: "Salisbury, NB"},
  {gov_id: 22878, name: "Shediac, NB"},
  {gov_id: 26535, name: "Grande-Digue, NB"},
  {gov_id: 26483, name: "Barachois, NB"},
  {gov_id: 26614, name: "Robichaud, NB"},
  {gov_id: 26198, name: "Petitcodiac, NB"},
  {gov_id: 26203, name: "Riverside-Albert, NB"},
  {gov_id: 22877, name: "Sackville, NB"},
  {gov_id: 22871, name: "Bouctouche, NB"},
  {gov_id: 26188, name: "Cap-Pele, NB"},
  {gov_id: 40862, name: "Aulac, NB"},
  {gov_id: 22386, name: "St. John's, NL"},
  {gov_id: 41594, name: "Shea Heights, NL"},
  {gov_id: 22385, name: "Mount Pearl, NL"},
  {gov_id: 22988, name: "Petty Harbour-Maddox Cove, NL"},
  {gov_id: 23026, name: "Torbay, NL"},
  {gov_id: 22995, name: "Portugal Cove-St. Philip's, NL"},
  {gov_id: 22985, name: "Paradise, NL"},
  {gov_id: 50131, name: "Conception Bay South, NL"},
  {gov_id: 22888, name: "Bay Bulls, NL"},
  {gov_id: 39310, name: "Witless Bay, NL"},
  {gov_id: 27834, name: "Harbour Main, NL"},
  {gov_id: 39303, name: "Holyrood, NL"},
  {gov_id: 27945, name: "Port de Grave, NL"},
  {gov_id: 23030, name: "Upper Island Cove, NL"},
  {gov_id: 22944, name: "Harbour Grace, NL"},
  {gov_id: 22891, name: "Bay Roberts, NL"},
  {gov_id: 22911, name: "Clarke's Beach, NL"},
  {gov_id: 23018, name: "Spaniard's Bay, NL"},
  {gov_id: 39074, name: "Carbonear, NL"},
  {gov_id: 27525, name: "North River, NL"},
  {gov_id: 28083, name: "Makinsons, NL"}
])
Market.create!([
  {noc_id: 11, name: " Legislators"},
  {noc_id: 12, name: "Senior Government Managers and Officials"},
  {noc_id: 13, name: "Senior Managers - Financial, Communications and Other Business Services"},
  {noc_id: 14, name: "Senior Managers - Health, Education, Social and Community Services and Membership Organizations"},
  {noc_id: 15, name: "Senior Managers - Trade, Broadcasting and Other Services, n.e.c."},
  {noc_id: 16, name: "Senior Managers - Goods Production, Utilities, Transportation and Construction"},
  {noc_id: 111, name: "Financial Managers"},
  {noc_id: 112, name: "Human Resources Managers"},
  {noc_id: 113, name: "Purchasing Managers"},
  {noc_id: 114, name: "Other Administrative Services Managers"},
  {noc_id: 121, name: "Insurance, Real Estate and Financial Brokerage Managers"},
  {noc_id: 122, name: "Banking, Credit and Other Investment Managers"},
  {noc_id: 123, name: "Other Business Services Managers"},
  {noc_id: 131, name: "Telecommunication Carriers Managers"},
  {noc_id: 132, name: "Postal and Courier Services Managers"},
  {noc_id: 211, name: "Engineering Managers"},
  {noc_id: 212, name: "Architecture and Science Managers"},
  {noc_id: 213, name: "Computer and Information Systems Managers"},
  {noc_id: 311, name: "Managers in Health Care"},
  {noc_id: 312, name: "Administrators - Post-Secondary Education and Vocational Training"},
  {noc_id: 313, name: "School Principals and Administrators of Elementary and Secondary Education"},
  {noc_id: 314, name: "Managers in Social, Community and Correctional Services"},
  {noc_id: 411, name: "Government Managers - Health and Social Policy Development and Program Administration"},
  {noc_id: 412, name: "Government Managers - Economic Analysis, Policy Development and Program Administration"},
  {noc_id: 413, name: "Government Managers - Education Policy Development and Program Administration"},
  {noc_id: 414, name: "Other Managers in Public Administration"},
  {noc_id: 511, name: "Library, Archive, Museum and Art Gallery Managers"},
  {noc_id: 512, name: "Managers - Publishing, Motion Pictures, Broadcasting and Performing Arts"},
  {noc_id: 513, name: "Recreation, Sports and Fitness Program and Service Directors"},
  {noc_id: 611, name: "Sales, Marketing and Advertising Managers"},
  {noc_id: 621, name: "Retail Trade Managers"},
  {noc_id: 631, name: "Restaurant and Food Service Managers"},
  {noc_id: 632, name: "Accommodation Service Managers"},
  {noc_id: 641, name: "Commissioned Police Officers"},
  {noc_id: 642, name: "Fire Chiefs and Senior Firefighting Officers"},
  {noc_id: 643, name: "Commissioned Officers, Armed Forces"},
  {noc_id: 651, name: "Other Services Managers"},
  {noc_id: 711, name: "Construction Managers"},
  {noc_id: 712, name: "Residential Home Builders and Renovators"},
  {noc_id: 713, name: "Transportation Managers"},
  {noc_id: 721, name: "Facility Operation and Maintenance Managers"},
  {noc_id: 811, name: "Primary Production Managers (Except Agriculture)"},
  {noc_id: 911, name: "Manufacturing Managers"},
  {noc_id: 912, name: "Utilities Managers"},
  {noc_id: 1111, name: "Financial Auditors and Accountants"},
  {noc_id: 1112, name: "Financial and Investment Analysts"},
  {noc_id: 1113, name: "Securities Agents, Investment Dealers and Brokers"},
  {noc_id: 1114, name: "Other Financial Officers"},
  {noc_id: 1121, name: "Specialists in Human Resources"},
  {noc_id: 1122, name: "Professional Occupations in Business Services to Management"},
  {noc_id: 1211, name: "Supervisors, General Office and Administrative Support Clerks"},
  {noc_id: 1212, name: "Supervisors, Finance and Insurance Clerks"},
  {noc_id: 1213, name: "Supervisors, Library, Correspondence and Related Information Clerks"},
  {noc_id: 1214, name: "Supervisors, Mail and Message Distribution Occupations"},
  {noc_id: 1215, name: "Supervisors, Recording, Distributing and Scheduling Occupations"},
  {noc_id: 1221, name: "Administrative Officers"},
  {noc_id: 1222, name: "Executive Assistants"},
  {noc_id: 1223, name: "Personnel and Recruitment Officers"},
  {noc_id: 1224, name: "Property Administrators"},
  {noc_id: 1225, name: "Purchasing Agents and Officers"},
  {noc_id: 1226, name: "Conference and Event Planners"},
  {noc_id: 1227, name: "Court Officers and Justices of the Peace"},
  {noc_id: 1228, name: "Immigration, Employment Insurance and Revenue Officers"},
  {noc_id: 1231, name: "Bookkeepers"},
  {noc_id: 1232, name: "Loan Officers"},
  {noc_id: 1233, name: "Insurance Adjusters and Claims Examiners"},
  {noc_id: 1234, name: "Insurance Underwriters"},
  {noc_id: 1235, name: "Assessors, Valuators and Appraisers"},
  {noc_id: 1236, name: "Customs, Ship and Other Brokers"},
  {noc_id: 1241, name: "Secretaries (Except Legal and Medical)"},
  {noc_id: 1242, name: "Legal Secretaries"},
  {noc_id: 1243, name: "Medical Secretaries"},
  {noc_id: 1244, name: "Court Recorders and Medical Transcriptionists"},
  {noc_id: 1411, name: "General Office Clerks"},
  {noc_id: 1413, name: "Records Management and Filing Clerks"},
  {noc_id: 1414, name: "Receptionists and Switchboard Operators"},
  {noc_id: 1422, name: "Data Entry Clerks"},
  {noc_id: 1423, name: "Desktop Publishing Operators and Related Occupations"},
  {noc_id: 1424, name: "Telephone Operators"},
  {noc_id: 1431, name: "Accounting and Related Clerks"},
  {noc_id: 1432, name: "Payroll Clerks"},
  {noc_id: 1433, name: "Customer Service Representatives - Financial Services"},
  {noc_id: 1434, name: "Banking, Insurance and Other Financial Clerks"},
  {noc_id: 1435, name: "Collectors"},
  {noc_id: 1441, name: "Administrative Clerks"},
  {noc_id: 1442, name: "Personnel Clerks"},
  {noc_id: 1443, name: "Court Clerks"},
  {noc_id: 1451, name: "Library Clerks"},
  {noc_id: 1452, name: "Correspondence, Publication and Related Clerks"},
  {noc_id: 1453, name: "Customer Service, Information and Related Clerks"},
  {noc_id: 1454, name: "Survey Interviewers and Statistical Clerks"},
  {noc_id: 1461, name: "Mail, Postal and Related Clerks"},
  {noc_id: 1462, name: "Letter Carriers"},
  {noc_id: 1463, name: "Couriers, Messengers and Door-to-Door Distributors"},
  {noc_id: 1471, name: "Shippers and Receivers"},
  {noc_id: 1472, name: "Storekeepers and Parts Clerks"},
  {noc_id: 1473, name: "Production Clerks"},
  {noc_id: 1474, name: "Purchasing and Inventory Clerks"},
  {noc_id: 1475, name: "Dispatchers and Radio Operators"},
  {noc_id: 1476, name: "Transportation Route and Crew Schedulers"},
  {noc_id: 2111, name: "Physicists and Astronomers"},
  {noc_id: 2112, name: "Chemists"},
  {noc_id: 2113, name: "Geologists, Geochemists and Geophysicists"},
  {noc_id: 2114, name: "Meteorologists"},
  {noc_id: 2115, name: "Other Professional Occupations in Physical Sciences"},
  {noc_id: 2121, name: "Biologists and Related Scientists"},
  {noc_id: 2122, name: "Forestry Professionals"},
  {noc_id: 2123, name: "Agricultural Representatives, Consultants and Specialists"},
  {noc_id: 2131, name: "Civil Engineers"},
  {noc_id: 2132, name: "Mechanical Engineers"},
  {noc_id: 2133, name: "Electrical and Electronics Engineers"},
  {noc_id: 2134, name: "Chemical Engineers"},
  {noc_id: 2141, name: "Industrial and Manufacturing Engineers"},
  {noc_id: 2142, name: "Metallurgical and Materials Engineers"},
  {noc_id: 2143, name: "Mining Engineers"},
  {noc_id: 2144, name: "Geological Engineers"},
  {noc_id: 2145, name: "Petroleum Engineers"},
  {noc_id: 2146, name: "Aerospace Engineers"},
  {noc_id: 2147, name: "Computer Engineers (Except Software Engineers and Designers)"},
  {noc_id: 2148, name: "Other Professional Engineers, n.e.c."},
  {noc_id: 2151, name: "Architects"},
  {noc_id: 2152, name: "Landscape Architects"},
  {noc_id: 2153, name: "Urban and Land Use Planners"},
  {noc_id: 2154, name: "Land Surveyors"},
  {noc_id: 2161, name: "Mathematicians, Statisticians and Actuaries"},
  {noc_id: 2171, name: "Information Systems Analysts and Consultants"},
  {noc_id: 2172, name: "Database Analysts and Data Administrators"},
  {noc_id: 2173, name: "Software Engineers and Designers"},
  {noc_id: 2174, name: "Computer Programmers and Interactive Media Developers"},
  {noc_id: 2175, name: "Web Designers and Developers"},
  {noc_id: 2211, name: "Chemical Technologists and Technicians"},
  {noc_id: 2212, name: "Geological and Mineral Technologists and Technicians"},
  {noc_id: 2213, name: "Meteorological Technicians"},
  {noc_id: 2221, name: "Biological Technologists and Technicians"},
  {noc_id: 2222, name: "Agricultural and Fish Products Inspectors"},
  {noc_id: 2223, name: "Forestry Technologists and Technicians"},
  {noc_id: 2224, name: "Conservation and Fishery Officers"},
  {noc_id: 2225, name: "Landscape and Horticulture Technicians and Specialists"},
  {noc_id: 2231, name: "Civil Engineering Technologists and Technicians"},
  {noc_id: 2232, name: "Mechanical Engineering Technologists and Technicians"},
  {noc_id: 2233, name: "Industrial Engineering and Manufacturing Technologists and Technicians"},
  {noc_id: 2234, name: "Construction Estimators"},
  {noc_id: 2241, name: "Electrical and Electronics Engineering Technologists and Technicians"},
  {noc_id: 2242, name: "Electronic Service Technicians (Household and Business Equipment)"},
  {noc_id: 2243, name: "Industrial Instrument Technicians and Mechanics"},
  {noc_id: 2244, name: "Aircraft Instrument, Electrical and Avionics Mechanics, Technicians and Inspectors"},
  {noc_id: 2251, name: "Architectural Technologists and Technicians"},
  {noc_id: 2252, name: "Industrial Designers"},
  {noc_id: 2253, name: "Drafting Technologists and Technicians"},
  {noc_id: 2254, name: "Land Survey Technologists and Technicians"},
  {noc_id: 2255, name: "Mapping and Related Technologists and Technicians"},
  {noc_id: 2261, name: "Non-Destructive Testers and Inspectors"},
  {noc_id: 2262, name: "Engineering Inspectors and Regulatory Officers"},
  {noc_id: 2263, name: "Inspectors in Public and Environmental Health and Occupational Health and Safety"},
  {noc_id: 2264, name: "Construction Inspectors"},
  {noc_id: 2271, name: "Air Pilots, Flight Engineers and Flying Instructors"},
  {noc_id: 2272, name: "Air Traffic Control and Related Occupations"},
  {noc_id: 2273, name: "Deck Officers, Water Transport"},
  {noc_id: 2274, name: "Engineer Officers, Water Transport"},
  {noc_id: 2275, name: "Railway Traffic Controllers and Marine Traffic Regulators"},
  {noc_id: 2281, name: "Computer Network Technicians"},
  {noc_id: 2282, name: "User Support Technicians"},
  {noc_id: 2283, name: "Systems Testing Technicians"},
  {noc_id: 3111, name: "Specialist Physicians"},
  {noc_id: 3112, name: "General Practitioners and Family Physicians"},
  {noc_id: 3113, name: "Dentists"},
  {noc_id: 3114, name: "Veterinarians"},
  {noc_id: 3121, name: "Optometrists"},
  {noc_id: 3122, name: "Chiropractors"},
  {noc_id: 3123, name: "Other Professional Occupations in Health Diagnosing and Treating"},
  {noc_id: 3131, name: "Pharmacists"},
  {noc_id: 3132, name: "Dietitians and Nutritionists"},
  {noc_id: 3141, name: "Audiologists and Speech-Language Pathologists"},
  {noc_id: 3142, name: "Physiotherapists"},
  {noc_id: 3143, name: "Occupational Therapists"},
  {noc_id: 3144, name: "Other Professional Occupations in Therapy and Assessment"},
  {noc_id: 3151, name: "Head Nurses and Supervisors"},
  {noc_id: 3152, name: "Registered Nurses"},
  {noc_id: 3211, name: "Medical Laboratory Technologists and Pathologists' Assistants"},
  {noc_id: 3212, name: "Medical Laboratory Technicians"},
  {noc_id: 3213, name: "Veterinary and Animal Health Technologists and Technicians"},
  {noc_id: 3214, name: "Respiratory Therapists, Clinical Perfusionists and Cardiopulmonary Technologists"},
  {noc_id: 3215, name: "Medical Radiation Technologists"},
  {noc_id: 3216, name: "Medical Sonographers"},
  {noc_id: 3217, name: "Cardiology Technologists"},
  {noc_id: 3218, name: "Electroencephalographic and Other Diagnostic Technologists, n.e.c."},
  {noc_id: 3219, name: "Other Medical Technologists and Technicians (Except Dental Health)"},
  {noc_id: 3221, name: "Denturists"},
  {noc_id: 3222, name: "Dental Hygienists and Dental Therapists"},
  {noc_id: 3223, name: "Dental Technologists, Technicians and Laboratory Bench Workers"},
  {noc_id: 3231, name: "Opticians"},
  {noc_id: 3232, name: "Midwives and Practitioners of Natural Healing"},
  {noc_id: 3233, name: "Licensed Practical Nurses"},
  {noc_id: 3234, name: "Ambulance Attendants and Other Paramedical Occupations"},
  {noc_id: 3235, name: "Other Technical Occupations in Therapy and Assessment"},
  {noc_id: 3411, name: "Dental Assistants"},
  {noc_id: 3413, name: "Nurse Aides, Orderlies and Patient Service Associates"},
  {noc_id: 3414, name: "Other Assisting Occupations in Support of Health Services"},
  {noc_id: 4111, name: "Judges"},
  {noc_id: 4112, name: "Lawyers and Quebec Notaries"},
  {noc_id: 4121, name: "University Professors"},
  {noc_id: 4122, name: "Post-Secondary Teaching and Research Assistants"},
  {noc_id: 4131, name: "College and Other Vocational Instructors"},
  {noc_id: 4141, name: "Secondary School Teachers"},
  {noc_id: 4142, name: "Elementary School and Kindergarten Teachers"},
  {noc_id: 4143, name: "Educational Counsellors"},
  {noc_id: 4151, name: "Psychologists"},
  {noc_id: 4152, name: "Social Workers"},
  {noc_id: 4153, name: "Family, Marriage and Other Related Counsellors"},
  {noc_id: 4154, name: "Ministers of Religion"},
  {noc_id: 4155, name: "Probation and Parole Officers and Related Occupations"},
  {noc_id: 4161, name: "Natural and Applied Science Policy Researchers, Consultants and Program Officers"},
  {noc_id: 4162, name: "Economists and Economic Policy Researchers and Analysts"},
  {noc_id: 4163, name: "Business Development Officers and Marketing Researchers and Consultants"},
  {noc_id: 4164, name: "Social Policy Researchers, Consultants and Program Officers"},
  {noc_id: 4165, name: "Health Policy Researchers, Consultants and Program Officers"},
  {noc_id: 4166, name: "Education Policy Researchers, Consultants and Program Officers"},
  {noc_id: 4167, name: "Recreation, Sports and Fitness Program Supervisors and Consultants"},
  {noc_id: 4168, name: "Program Officers Unique to Government"},
  {noc_id: 4169, name: "Other Professional Occupations in Social Science, n.e.c."},
  {noc_id: 4211, name: "Paralegal and Related Occupations"},
  {noc_id: 4212, name: "Community and Social Service Workers"},
  {noc_id: 4213, name: "Employment Counsellors"},
  {noc_id: 4214, name: "Early Childhood Educators and Assistants"},
  {noc_id: 4215, name: "Instructors and Teachers of Persons with Disabilities"},
  {noc_id: 4216, name: "Other Instructors"},
  {noc_id: 4217, name: "Other Religious Occupations"},
  {noc_id: 5111, name: "Librarians"},
  {noc_id: 5112, name: "Conservators and Curators"},
  {noc_id: 5113, name: "Archivists"},
  {noc_id: 5121, name: "Authors and Writers"},
  {noc_id: 5122, name: "Editors"},
  {noc_id: 5123, name: "Journalists"},
  {noc_id: 5124, name: "Professional Occupations in Public Relations and Communications"},
  {noc_id: 5125, name: "Translators, Terminologists and Interpreters"},
  {noc_id: 5131, name: "Producers, Directors, Choreographers and Related Occupations"},
  {noc_id: 5132, name: "Conductors, Composers and Arrangers"},
  {noc_id: 5133, name: "Musicians and Singers"},
  {noc_id: 5134, name: "Dancers"},
  {noc_id: 5135, name: "Actors and Comedians"},
  {noc_id: 5136, name: "Painters, Sculptors and Other Visual Artists"},
  {noc_id: 5211, name: "Library and Archive Technicians and Assistants"},
  {noc_id: 5212, name: "Technical Occupations Related to Museums and Art Galleries"},
  {noc_id: 5221, name: "Photographers"},
  {noc_id: 5222, name: "Film and Video Camera Operators"},
  {noc_id: 5223, name: "Graphic Arts Technicians"},
  {noc_id: 5224, name: "Broadcast Technicians"},
  {noc_id: 5225, name: "Audio and Video Recording Technicians"},
  {noc_id: 5226, name: "Other Technical and Co-ordinating Occupations in Motion Pictures, Broadcasting and the Performing Arts"},
  {noc_id: 5227, name: "Support Occupations in Motion Pictures, Broadcasting and the Performing Arts"},
  {noc_id: 5231, name: "Announcers and Other Broadcasters"},
  {noc_id: 5232, name: "Other Performers"},
  {noc_id: 5241, name: "Graphic Designers and Illustrators"},
  {noc_id: 5242, name: "Interior Designers"},
  {noc_id: 5243, name: "Theatre, Fashion, Exhibit and Other Creative Designers"},
  {noc_id: 5244, name: "Artisans and Craftspersons"},
  {noc_id: 5245, name: "Patternmakers - Textile, Leather and Fur Products"},
  {noc_id: 5251, name: "Athletes"},
  {noc_id: 5252, name: "Coaches"},
  {noc_id: 5253, name: "Sports Officials and Referees"},
  {noc_id: 5254, name: "Program Leaders and Instructors in Recreation, Sport and Fitness"},
  {noc_id: 6211, name: "Retail Trade Supervisors"},
  {noc_id: 6212, name: "Food Service Supervisors"},
  {noc_id: 6213, name: "Executive Housekeepers"},
  {noc_id: 6214, name: "Dry Cleaning and Laundry Supervisors"},
  {noc_id: 6215, name: "Cleaning Supervisors"},
  {noc_id: 6216, name: "Other Service Supervisors"},
  {noc_id: 6221, name: "Technical Sales Specialists - Wholesale Trade"},
  {noc_id: 6231, name: "Insurance Agents and Brokers"},
  {noc_id: 6232, name: "Real Estate Agents and Salespersons"},
  {noc_id: 6233, name: "Retail and Wholesale Buyers"},
  {noc_id: 6234, name: "Grain Elevator Operators"},
  {noc_id: 6241, name: "Chefs"},
  {noc_id: 6242, name: "Cooks"},
  {noc_id: 6251, name: "Butchers, Meat Cutters and Fishmongers - Retail and Wholesale"},
  {noc_id: 6252, name: "Bakers"},
  {noc_id: 6261, name: "Police Officers (Except Commissioned)"},
  {noc_id: 6262, name: "Firefighters"},
  {noc_id: 6271, name: "Hairstylists and Barbers"},
  {noc_id: 6272, name: "Funeral Directors and Embalmers"},
  {noc_id: 6411, name: "Sales Representatives - Wholesale Trade (Non-Technical)"},
  {noc_id: 6421, name: "Retail Salespersons and Sales Clerks"},
  {noc_id: 6431, name: "Travel Counsellors"},
  {noc_id: 6432, name: "Pursers and Flight Attendants"},
  {noc_id: 6433, name: "Airline Sales and Service Agents"},
  {noc_id: 6434, name: "Ticket Agents, Cargo Service Representatives and Related Clerks (Except Airline)"},
  {noc_id: 6435, name: "Hotel Front Desk Clerks"},
  {noc_id: 6441, name: "Tour and Travel Guides"},
  {noc_id: 6442, name: "Outdoor Sport and Recreational Guides"},
  {noc_id: 6443, name: "Casino Occupations"},
  {noc_id: 6451, name: "Maitres d'hotel and Hosts/Hostesses"},
  {noc_id: 6452, name: "Bartenders"},
  {noc_id: 6453, name: "Food and Beverage Servers"},
  {noc_id: 6461, name: "Sheriffs and Bailiffs"},
  {noc_id: 6462, name: "Correctional Service Officers"},
  {noc_id: 6463, name: "By-Law Enforcement and Other Regulatory Officers, n.e.c."},
  {noc_id: 6464, name: "Occupations Unique to the Armed Forces"},
  {noc_id: 6465, name: "Other Protective Service Occupations"},
  {noc_id: 6471, name: "Visiting Homemakers, Housekeepers and Related Occupations"},
  {noc_id: 6472, name: "Elementary and Secondary School Teacher Assistants"},
  {noc_id: 6474, name: "Babysitters, Nannies and Parents' Helpers"},
  {noc_id: 6481, name: "Image, Social and Other Personal Consultants"},
  {noc_id: 6482, name: "Estheticians, Electrologists and Related Occupations"},
  {noc_id: 6483, name: "Pet Groomers and Animal Care Workers"},
  {noc_id: 6484, name: "Other Personal Service Occupations"},
  {noc_id: 6611, name: "Cashiers"},
  {noc_id: 6621, name: "Service Station Attendants"},
  {noc_id: 6622, name: "Grocery Clerks and Store Shelf Stockers"},
  {noc_id: 6623, name: "Other Elemental Sales Occupations"},
  {noc_id: 6641, name: "Food Counter Attendants, Kitchen Helpers and Related Occupations"},
  {noc_id: 6651, name: "Security Guards and Related Occupations"},
  {noc_id: 6661, name: "Light Duty Cleaners"},
  {noc_id: 6662, name: "Specialized Cleaners"},
  {noc_id: 6663, name: "Janitors, Caretakers and Building Superintendents"},
  {noc_id: 6671, name: "Operators and Attendants in Amusement, Recreation and Sport"},
  {noc_id: 6672, name: "Other Attendants in Accommodation and Travel"},
  {noc_id: 6681, name: "Dry Cleaning and Laundry Occupations"},
  {noc_id: 6682, name: "Ironing, Pressing and Finishing Occupations"},
  {noc_id: 6683, name: "Other Elemental Service Occupations"},
  {noc_id: 7211, name: "Supervisors, Machinists and Related Occupations"},
  {noc_id: 7212, name: "Contractors and Supervisors, Electrical Trades and Telecommunications Occupations"},
  {noc_id: 7213, name: "Contractors and Supervisors, Pipefitting Trades"},
  {noc_id: 7214, name: "Contractors and Supervisors, Metal Forming, Shaping and Erecting Trades"},
  {noc_id: 7215, name: "Contractors and Supervisors, Carpentry Trades"},
  {noc_id: 7216, name: "Contractors and Supervisors, Mechanic Trades"},
  {noc_id: 7217, name: "Contractors and Supervisors, Heavy Construction Equipment Crews"},
  {noc_id: 7218, name: "Supervisors, Printing and Related Occupations"},
  {noc_id: 7219, name: "Contractors and Supervisors, Other Construction Trades, Installers, Repairers and Servicers"},
  {noc_id: 7221, name: "Supervisors, Railway Transport Operations"},
  {noc_id: 7222, name: "Supervisors, Motor Transport and Other Ground Transit Operators"},
  {noc_id: 7231, name: "Machinists and Machining and Tooling Inspectors"},
  {noc_id: 7232, name: "Tool and Die Makers"},
  {noc_id: 7241, name: "Electricians (Except Industrial and Power System)"},
  {noc_id: 7242, name: "Industrial Electricians"},
  {noc_id: 7243, name: "Power System Electricians"},
  {noc_id: 7244, name: "Electrical Power Line and Cable Workers"},
  {noc_id: 7245, name: "Telecommunications Line and Cable Workers"},
  {noc_id: 7246, name: "Telecommunications Installation and Repair Workers"},
  {noc_id: 7247, name: "Cable Television Service and Maintenance Technicians"},
  {noc_id: 7251, name: "Plumbers"},
  {noc_id: 7252, name: "Steamfitters, Pipefitters and Sprinkler System Installers"},
  {noc_id: 7253, name: "Gas Fitters"},
  {noc_id: 7261, name: "Sheet Metal Workers"},
  {noc_id: 7262, name: "Boilermakers"},
  {noc_id: 7263, name: "Structural Metal and Platework Fabricators and Fitters"},
  {noc_id: 7264, name: "Ironworkers"},
  {noc_id: 7265, name: "Welders and Related Machine Operators"},
  {noc_id: 7266, name: "Blacksmiths and Die Setters"},
  {noc_id: 7271, name: "Carpenters"},
  {noc_id: 7272, name: "Cabinetmakers"},
  {noc_id: 7281, name: "Bricklayers"},
  {noc_id: 7282, name: "Concrete Finishers"},
  {noc_id: 7283, name: "Tilesetters"},
  {noc_id: 7284, name: "Plasterers, Drywall Installers and Finishers and Lathers"},
  {noc_id: 7291, name: "Roofers and Shinglers"},
  {noc_id: 7292, name: "Glaziers"},
  {noc_id: 7293, name: "Insulators"},
  {noc_id: 7294, name: "Painters and Decorators"},
  {noc_id: 7295, name: "Floor Covering Installers"},
  {noc_id: 7311, name: "Construction Millwrights and Industrial Mechanics (Except Textile)"},
  {noc_id: 7312, name: "Heavy-Duty Equipment Mechanics"},
  {noc_id: 7313, name: "Refrigeration and Air Conditioning Mechanics"},
  {noc_id: 7314, name: "Railway Carmen/women"},
  {noc_id: 7315, name: "Aircraft Mechanics and Aircraft Inspectors"},
  {noc_id: 7316, name: "Machine Fitters"},
  {noc_id: 7317, name: "Textile Machinery Mechanics and Repairers"},
  {noc_id: 7318, name: "Elevator Constructors and Mechanics"},
  {noc_id: 7321, name: "Automotive Service Technicians, Truck and Bus Mechanics and Mechanical Repairers"},
  {noc_id: 7322, name: "Motor Vehicle Body Repairers"},
  {noc_id: 7331, name: "Oil and Solid Fuel Heating Mechanics"},
  {noc_id: 7332, name: "Electric Appliance Servicers and Repairers"},
  {noc_id: 7333, name: "Electrical Mechanics"},
  {noc_id: 7334, name: "Motorcycle and Other Related Mechanics"},
  {noc_id: 7335, name: "Other Small Engine and Equipment Mechanics"},
  {noc_id: 7341, name: "Upholsterers"},
  {noc_id: 7342, name: "Tailors, Dressmakers, Furriers and Milliners"},
  {noc_id: 7343, name: "Shoe Repairers and Shoemakers"},
  {noc_id: 7344, name: "Jewellers, Watch Repairers and Related Occupations"},
  {noc_id: 7351, name: "Stationary Engineers and Auxiliary Equipment Operators"},
  {noc_id: 7352, name: "Power Systems and Power Station Operators"},
  {noc_id: 7361, name: "Railway and Yard Locomotive Engineers"},
  {noc_id: 7362, name: "Railway Conductors and Brakemen/women"},
  {noc_id: 7371, name: "Crane Operators"},
  {noc_id: 7372, name: "Drillers and Blasters - Surface Mining, Quarrying and Construction"},
  {noc_id: 7373, name: "Water Well Drillers"},
  {noc_id: 7381, name: "Printing Press Operators"},
  {noc_id: 7382, name: "Commercial Divers"},
  {noc_id: 7383, name: "Other Trades and Related Occupations"},
  {noc_id: 7411, name: "Truck Drivers"},
  {noc_id: 7412, name: "Bus Drivers, Subway Operators and Other Transit Operators"},
  {noc_id: 7413, name: "Taxi and Limousine Drivers and Chauffeurs"},
  {noc_id: 7414, name: "Delivery and Courier Service Drivers"},
  {noc_id: 7421, name: "Heavy Equipment Operators (Except Crane)"},
  {noc_id: 7422, name: "Public Works Maintenance Equipment Operators"},
  {noc_id: 7431, name: "Railway Yard Workers"},
  {noc_id: 7432, name: "Railway Track Maintenance Workers"},
  {noc_id: 7433, name: "Deck Crew, Water Transport"},
  {noc_id: 7434, name: "Engine Room Crew, Water Transport"},
  {noc_id: 7435, name: "Lock and Cable Ferry Operators and Related Occupations"},
  {noc_id: 7436, name: "Boat Operators"},
  {noc_id: 7437, name: "Air Transport Ramp Attendants"},
  {noc_id: 7441, name: "Residential and Commercial Installers and Servicers"},
  {noc_id: 7442, name: "Waterworks and Gas Maintenance Workers"},
  {noc_id: 7443, name: "Automotive Mechanical Installers and Servicers"},
  {noc_id: 7444, name: "Pest Controllers and Fumigators"},
  {noc_id: 7445, name: "Other Repairers and Servicers"},
  {noc_id: 7451, name: "Longshore Workers"},
  {noc_id: 7452, name: "Material Handlers"},
  {noc_id: 7611, name: "Construction Trades Helpers and Labourers"},
  {noc_id: 7612, name: "Other Trades Helpers and Labourers"},
  {noc_id: 7621, name: "Public Works and Maintenance Labourers"},
  {noc_id: 7622, name: "Railway and Motor Transport Labourers"},
  {noc_id: 8211, name: "Supervisors, Logging and Forestry"},
  {noc_id: 8221, name: "Supervisors, Mining and Quarrying"},
  {noc_id: 8222, name: "Supervisors, Oil and Gas Drilling and Service"},
  {noc_id: 8231, name: "Underground Production and Development Miners"},
  {noc_id: 8232, name: "Oil and Gas Well Drillers, Servicers, Testers and Related Workers"},
  {noc_id: 8241, name: "Logging Machinery Operators"},
  {noc_id: 8251, name: "Farmers and Farm Managers"},
  {noc_id: 8252, name: "Agricultural and Related Service Contractors and Managers"},
  {noc_id: 8253, name: "Farm Supervisors and Specialized Livestock Workers"},
  {noc_id: 8254, name: "Nursery and Greenhouse Operators and Managers"},
  {noc_id: 8255, name: "Landscaping and Grounds Maintenance Contractors and Managers"},
  {noc_id: 8256, name: "Supervisors, Landscape and Horticulture"},
  {noc_id: 8257, name: "Aquaculture Operators and Managers"},
  {noc_id: 8261, name: "Fishing Masters and Officers"},
  {noc_id: 8262, name: "Fishing Vessel Skippers and Fishermen/women"},
  {noc_id: 8411, name: "Underground Mine Service and Support Workers"},
  {noc_id: 8412, name: "Oil and Gas Well Drilling Workers and Services Operators"},
  {noc_id: 8421, name: "Chain Saw and Skidder Operators"},
  {noc_id: 8422, name: "Silviculture and Forestry Workers"},
  {noc_id: 8431, name: "General Farm Workers"},
  {noc_id: 8432, name: "Nursery and Greenhouse Workers"},
  {noc_id: 8441, name: "Fishing Vessel Deckhands"},
  {noc_id: 8442, name: "Trappers and Hunters"},
  {noc_id: 8611, name: "Harvesting Labourers"},
  {noc_id: 8612, name: "Landscaping and Grounds Maintenance Labourers"},
  {noc_id: 8613, name: "Aquaculture and Marine Harvest Labourers"},
  {noc_id: 8614, name: "Mine Labourers"},
  {noc_id: 8615, name: "Oil and Gas Drilling, Servicing and Related Labourers"},
  {noc_id: 8616, name: "Logging and Forestry Labourers"},
  {noc_id: 9211, name: "Supervisors, Mineral and Metal Processing"},
  {noc_id: 9212, name: "Supervisors, Petroleum, Gas and Chemical Processing and Utilities"},
  {noc_id: 9213, name: "Supervisors, Food, Beverage and Tobacco Processing"},
  {noc_id: 9214, name: "Supervisors, Plastic and Rubber Products Manufacturing"},
  {noc_id: 9215, name: "Supervisors, Forest Products Processing"},
  {noc_id: 9216, name: "Supervisors, Textile Processing"},
  {noc_id: 9221, name: "Supervisors, Motor Vehicle Assembling"},
  {noc_id: 9222, name: "Supervisors, Electronics Manufacturing"},
  {noc_id: 9223, name: "Supervisors, Electrical Products Manufacturing"},
  {noc_id: 9224, name: "Supervisors, Furniture and Fixtures Manufacturing"},
  {noc_id: 9225, name: "Supervisors, Fabric, Fur and Leather Products Manufacturing"},
  {noc_id: 9226, name: "Supervisors, Other Mechanical and Metal Products Manufacturing"},
  {noc_id: 9227, name: "Supervisors, Other Products Manufacturing and Assembly"},
  {noc_id: 9231, name: "Central Control and Process Operators, Mineral and Metal Processing"},
  {noc_id: 9232, name: "Petroleum, Gas and Chemical Process Operators"},
  {noc_id: 9233, name: "Pulping Control Operators"},
  {noc_id: 9234, name: "Papermaking and Coating Control Operators"},
  {noc_id: 9411, name: "Machine Operators, Mineral and Metal Processing"},
  {noc_id: 9412, name: "Foundry Workers"},
  {noc_id: 9413, name: "Glass Forming and Finishing Machine Operators and Glass Cutters"},
  {noc_id: 9414, name: "Concrete, Clay and Stone Forming Operators"},
  {noc_id: 9415, name: "Inspectors and Testers, Mineral and Metal Processing"},
  {noc_id: 9421, name: "Chemical Plant Machine Operators"},
  {noc_id: 9422, name: "Plastics Processing Machine Operators"},
  {noc_id: 9423, name: "Rubber Processing Machine Operators and Related Workers"},
  {noc_id: 9424, name: "Water and Waste Plant Operators"},
  {noc_id: 9431, name: "Sawmill Machine Operators"},
  {noc_id: 9432, name: "Pulp Mill Machine Operators"},
  {noc_id: 9433, name: "Papermaking and Finishing Machine Operators"},
  {noc_id: 9434, name: "Other Wood Processing Machine Operators"},
  {noc_id: 9435, name: "Paper Converting Machine Operators"},
  {noc_id: 9436, name: "Lumber Graders and Other Wood Processing Inspectors and Graders"},
  {noc_id: 9441, name: "Textile Fibre and Yarn Preparation Machine Operators"},
  {noc_id: 9442, name: "Weavers, Knitters and Other Fabric-Making Occupations"},
  {noc_id: 9443, name: "Textile Dyeing and Finishing Machine Operators"},
  {noc_id: 9444, name: "Textile Inspectors, Graders and Samplers"},
  {noc_id: 9451, name: "Sewing Machine Operators"},
  {noc_id: 9452, name: "Fabric, Fur and Leather Cutters"},
  {noc_id: 9453, name: "Hide and Pelt Processing Workers"},
  {noc_id: 9454, name: "Inspectors and Testers, Fabric, Fur and Leather Products Manufacturing"},
  {noc_id: 9461, name: "Process Control and Machine Operators, Food and Beverage Processing"},
  {noc_id: 9462, name: "Industrial Butchers and Meat Cutters, Poultry Preparers and Related Workers"},
  {noc_id: 9463, name: "Fish Plant Workers"},
  {noc_id: 9464, name: "Tobacco Processing Machine Operators"},
  {noc_id: 9465, name: "Testers and Graders, Food and Beverage Processing"},
  {noc_id: 9471, name: "Printing Machine Operators"},
  {noc_id: 9472, name: "Camera, Platemaking and Other Prepress Occupations"},
  {noc_id: 9473, name: "Binding and Finishing Machine Operators"},
  {noc_id: 9474, name: "Photographic and Film Processors"},
  {noc_id: 9481, name: "Aircraft Assemblers and Aircraft Assembly Inspectors"},
  {noc_id: 9482, name: "Motor Vehicle Assemblers, Inspectors and Testers"},
  {noc_id: 9483, name: "Electronics Assemblers, Fabricators, Inspectors and Testers"},
  {noc_id: 9491, name: "Boat Assemblers and Inspectors"},
  {noc_id: 9498, name: "Other Assemblers and Inspectors"},
  {noc_id: 9511, name: "Machining Tool Operators"},
  {noc_id: 9512, name: "Forging Machine Operators"},
  {noc_id: 9513, name: "Woodworking Machine Operators"},
  {noc_id: 9514, name: "Metalworking Machine Operators"},
  {noc_id: 9516, name: "Other Metal Products Machine Operators"},
  {noc_id: 9517, name: "Other Products Machine Operators"},
  {noc_id: 9611, name: "Labourers in Mineral and Metal Processing"},
  {noc_id: 9612, name: "Labourers in Metal Fabrication"},
  {noc_id: 9613, name: "Labourers in Chemical Products Processing and Utilities"},
  {noc_id: 9614, name: "Labourers in Wood, Pulp and Paper Processing"},
  {noc_id: 9615, name: "Labourers in Rubber and Plastic Products Manufacturing"},
  {noc_id: 9616, name: "Labourers in Textile Processing"},
  {noc_id: 9617, name: "Labourers in Food, Beverage and Tobacco Processing"},
  {noc_id: 9618, name: "Labourers in Fish Processing"},
  {noc_id: 9619, name: "Other Labourers in Processing, Manufacturing and Utilities"},
  {noc_id: 9484, name: "Assemblers and Inspectors, Electrical Appliance, Apparatus and Equipment Manufacturing"},
  {noc_id: 9485, name: "Assemblers, Fabricators and Inspectors, Industrial Electrical Motors and Transformers"},
  {noc_id: 9486, name: "Mechanical Assemblers and Inspectors"},
  {noc_id: 9487, name: "Machine Operators and Inspectors, Electrical Apparatus Manufacturing"},
  {noc_id: 9492, name: "Furniture and Fixture Assemblers and Inspectors"},
  {noc_id: 9493, name: "Other Wood Products Assemblers and Inspectors"},
  {noc_id: 9494, name: "Furniture Finishers and Refinishers"},
  {noc_id: 9495, name: "Plastic Products Assemblers, Finishers and Inspectors"},
  {noc_id: 9496, name: "Painters and Coaters - Industrial"},
  {noc_id: 9497, name: "Plating, Metal Spraying and Related Operators"}
])
